group_settings:
  description: "description from group settings"
  variables:
    RELEASE_VERSION:
      key: RELEASE_VERSION
      value: "Q4_28"
      description:
      # environment_scope: production
      filter:
      masked: false
      protected: false
      raw: false
      variable_type: env_var
    PYTHON_VERSION:
      key: PYTHON_VERSION
      value: "3.11.10"
      description: python version
      filter:
      masked: false
      protected: false
      raw: false
      variable_type: env_var
    SECRET_TOKEN:
      key: SECRET_TOKEN
      value: "test_secret_token_$VALUE"
      description: secret token
      filter:
      masked: true
      protected: true
      raw: true
      variable_type: env_var

project_settings:
  description: "description from project settings"
  variables:
    test:
      key: VAULT_ROLE
      value: "pivlab_ci_01"
      description: vault role name
      environment_scope: production
      filter:
      masked: true
      protected: true
      raw:
      variable_type: env_var
